PROGRAMME       = 'fg-list-container'
ITEM            = 'fg-list-item'
TIME            = 'fg-list-item-time'
CINEMA          = 'fg-list-item-cinema'
TITLE           = 'fg-list-item-title'
DESCRIPTION     = 'fg-list-item-description'
MINUTES         = 'min.'
